name: update-sources

on:
  workflow_call:
    secrets:
      SOURCE_DEPLOY_KEY:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-sources:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Install GNU Global
        run: sudo apt-get install -y global exuberant-ctags python3-pygments

      - name: Checkout source.midnight-commander.org repo
        uses: actions/checkout@v5
        with:
          repository: MidnightCommander/source
          path: HTML
          ref: gh-pages
          ssh-key: ${{ secrets.SOURCE_DEPLOY_KEY }}

      - name: Download rendered manual pages
        uses: actions/download-artifact@v4
        with:
          name: man-pages-html-${{ github.sha }}
          path: man

      - name: Create sources index
        run: |
          pushd HTML
            git switch --orphan gh-pages-new
          popd

          htags --gtags --suggest --tree-view --insert-header man/header.html \
            -t "Welcome to the Midnight Commander source tour!"
          ./maint/htagsfix

      - name: Deploy to GitHub
        run: |
          mv man HTML

          cd HTML

          touch .nojekyll
          echo "source.midnight-commander.org" > CNAME

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git add .
          git commit -m "Deploy to GitHub Pages"

          git push --force-with-lease origin HEAD:gh-pages
